PACKAGE_NAME="saa716x-capture"
PACKAGE_VERSION="0.1"
MODS="CONFIG_SAA716X_CORE=m CONFIG_SAA716X_CAPTURE=m CONFIG_MST3367=m CONFIG_ECHDCAP_RX=m"
MAKE[0]="make -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build ${MODS} modules"
CLEAN="make -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build clean"
BUILT_MODULE_NAME[0]="saa716x_core"
BUILT_MODULE_NAME[1]="saa716x_capture"
BUILT_MODULE_NAME[2]="echdcap_rx"
BUILT_MODULE_NAME[3]="mst3367-drv"
DEST_MODULE_LOCATION[0]="/updates/dkms"
DEST_MODULE_LOCATION[1]="/updates/dkms"
DEST_MODULE_LOCATION[2]="/updates/dkms"
DEST_MODULE_LOCATION[3]="/updates/dkms"
AUTOINSTALL="yes"
